alias: Den_Party
description: Randomly change light color in den for a party
trigger:
  - platform: mqtt
    topic: den/party_light
condition: []
action:
  - repeat:
      count: 10
      sequence:
        - service: light.turn_on
          entity_id: light.signify_netherlands_b_v_lcb002_light
          data:
            rgb_color:
              - "{{ range(0, 256)|random }}"
              - "{{ range(0, 256)|random }}"
              - "{{ range(0, 256)|random }}"
        - delay:
            seconds: 1
mode: single