alias: Den_Green
description: Turn on green light in den
trigger:
  - platform: mqtt
    topic: den/green_light
condition: []
action:
  - service: light.turn_on
    entity_id: light.signify_netherlands_b_v_lcb002_light
    data:
      rgb_color:
        - 0
        - 255
        - 0
mode: single
