alias: Den_White
description: Turn on plain white light in den
trigger:
  - platform: mqtt
    topic: den/white_light
condition: []
action:
  - service: light.turn_on
    entity_id: light.signify_netherlands_b_v_lcb002_light
    data:
      rgb_color:
        - 255
        - 255
        - 255
mode: single
