alias: Kitchen_Blue
description: Turn on blue light in kitchen
trigger:
  - platform: mqtt
    topic: kitchen/blue_light
condition: []
action:
  - service: light.turn_on
    entity_id: light.signify_netherlands_b_v_lcb002_light_2
    data:
      rgb_color:
        - 0
        - 0
        - 255
mode: single