alias: Kitchen_White
description: Turn on plain white light in kitchen
trigger:
  - platform: mqtt
    topic: kitchen/white_light
condition: []
action:
  - service: light.turn_on
    entity_id: light.signify_netherlands_b_v_lcb002_light_2
    data:
      rgb_color:
        - 255
        - 255
        - 255
mode: single
