alias: Kitchen_Green
description: Turn on green light in kitchen
trigger:
  - platform: mqtt
    topic: kitchen/green_light
condition: []
action:
  - service: light.turn_on
    entity_id: light.signify_netherlands_b_v_lcb002_light_2
    data:
      rgb_color:
        - 0
        - 255
        - 0
mode: single
